name: learnlab
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter

    cupertino_icons: ^1.0.2
    google_fonts: ^2.0.0

    firebase_core: ^1.3.0
    firebase_analytics: ^8.1.2
    cloud_firestore: ^2.3.0

    image_picker: ^0.8.3+2
    image_cropper: ^1.4.1
    firebase_storage: ^10.0.1

    firebase_auth: ^2.0.0

    firebase_messaging: ^10.0.6

    provider: ^5.0.0
    font_awesome_flutter: ^9.0.0

    flutter_native_splash: ^1.2.0
    flutter_launcher_icons: ^0.9.1

    fl_chart: ^0.36.3

flutter_native_splash:
    color: "#74C1C6"
    image: assets/images/logo_text_640.png
    android: true
    ios: true
    fullscreen: true

flutter_icons:
    android: true
    ios: true
    image_path_android: assets/images/icon_android.png
    image_path_ios: assets/images/icon_ios.png
    adaptive_icon_background: "#74C1C6"
    adaptive_icon_foreground: assets/images/fg_android.png

dev_dependencies:
    flutter_test:
        sdk: flutter

    import_sorter: ^4.5.1
    lint: ^1.5.3

flutter:
    uses-material-design: true

    assets:
        - assets/images/
        - assets/images/characters/
